# Semana 1 - Fundamentos de engenharia de dados

# Base de Dados

A base utilizada nas análises é “Brasil real estate Data”, disponível no [Kaggle](https://https://www.kaggle.com/datasets/ashishkumarjayswal/brasil-real-estate?resource=download). O conjunto de dados contém informações sobre imóveis disponíveis para venda ou aluguel no Brasil. Inclui detalhes como tipo de imóvel (apartamento ou casa), localização (latitude e longitude), tamanho (área/m²), preço e região. Este conjunto de dados pode ser usado para análise de mercado, avaliação de propriedades e identificação de tendências no mercado imobiliário.

## Importando dos dados

In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [38]:
df = pd.read_csv("https://raw.githubusercontent.com/Annalicefs/Engenharia-de-Dados_PANDA/main/pratica%201/Brasile-real-estate-dataset.csv", encoding_errors='replace')

In [18]:
df.head()

,Unnamed: 0,property_type,state,region,lat,lon,area_m2,price_brl
0,1,apartment,Pernambuco,Northeast,-8.134204,-34.906326,72.0,414222.98
1,2,apartment,Pernambuco,Northeast,-8.126664,-34.903924,136.0,848408.53
2,3,apartment,Pernambuco,Northeast,-8.125550,-34.907601,75.0,299438.28
3,4,apartment,Pernambuco,Northeast,-8.120249,-34.895920,187.0,848408.53
4,5,apartment,Pernambuco,Northeast,-8.142666,-34.906906,80.0,464129.36

In [19]:
df.tail()

,Unnamed: 0,property_type,state,region,lat,lon,area_m2,price_brl
12828,12829,house,S�o Paulo,Southeast,-23.587495,-46.559401,250.0,429194.89
12829,12830,apartment,S�o Paulo,Southeast,-23.522029,-46.189290,55.0,252398.80
12830,12831,apartment,S�o Paulo,Southeast,-23.526443,-46.529182,57.0,319400.84
12831,12832,house,Tocantins,North,-8.848399,-48.511164,NaN,529007.65
12832,12833,apartment,Tocantins,North,-10.249091,-48.324286,70.0,289457.01

In [21]:
df.describe()

         Unnamed: 0           lat           lon       area_m2     price_brl
count  12833.000000  12833.000000  12833.000000  11293.000000  1.283300e+04
mean    6417.000000    -24.689864    -46.753962    113.306916  6.652324e+05
std     3704.712337      5.377947      4.221204     47.225496  3.477194e+05
min        1.000000    -33.692432    -63.905184     53.000000  2.395506e+05
25%     3209.000000    -27.748068    -49.057643     75.000000  3.886942e+05
50%     6417.000000    -23.687899    -46.864044    101.000000  5.689328e+05
75%     9625.000000    -22.955832    -43.360172    140.000000  8.504048e+05
max    12833.000000     -5.044685    -34.841721    252.000000  1.676854e+06

## Pré-processamento

Como foi possível obervar pelas últimas linhas do dataset, os estados com acento estão com problema de codificação.

In [22]:
df['state'].unique()

array(['Pernambuco', 'Piau�', 'Rio Grande do Norte', 'Rio Grande do Sul',
       'Rio de Janeiro', 'Rond�nia', 'Santa Catarina', 'Sergipe',
       'S�o Paulo', 'Tocantins'], dtype=object)

Corrigindo manualmente o problema colocando os caracteres corretos.

In [39]:
df['state'] = df['state'].str.replace('S�o Paulo', 'São Paulo')
df['state'] = df['state'].str.replace('Piau�', 'Piauí')
df['state'] = df['state'].str.replace('Rond�nia', 'Rondônia')

In [25]:
df['state'].unique()

array(['Pernambuco', 'Piauí', 'Rio Grande do Norte', 'Rio Grande do Sul',
       'Rio de Janeiro', 'Rondônia', 'Santa Catarina', 'Sergipe',
       'São Paulo', 'Tocantins'], dtype=object)

### Valores nulos

Verificação do tipo de cada atributo, totais e possíveis ausências de valores. \
É possível visualizar que o atributo 'area_m2' possui valores nulos.

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12833 entries, 0 to 12832
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     12833 non-null  int64
 1   property_type  12833 non-null  object
 2   state          12833 non-null  object
 3   region         12833 non-null  object
 4   lat            12833 non-null  float64
 5   lon            12833 non-null  float64
 6   area_m2        11293 non-null  float64
 7   price_brl      12833 non-null  float64
dtypes: float64(4), int64(1), object(3)
memory usage: 802.2+ KB

In [27]:
df.isnull().sum()

Unnamed: 0          0
property_type       0
state               0
region              0
lat                 0
lon                 0
area_m2          1540
price_brl           0
dtype: int64

Exclusão das linhas em que a área tem valor nulo.

In [43]:
df = df.dropna()

In [44]:
df

,Unnamed: 0,property_type,state,region,lat,lon,area_m2,price_brl,price_per_m2
0,1,apartment,Pernambuco,Northeast,-8.134204,-34.906326,72.0,414222.98,5753.096944
1,2,apartment,Pernambuco,Northeast,-8.126664,-34.903924,136.0,848408.53,6238.298015
2,3,apartment,Pernambuco,Northeast,-8.125550,-34.907601,75.0,299438.28,3992.510400
3,4,apartment,Pernambuco,Northeast,-8.120249,-34.895920,187.0,848408.53,4536.944011
4,5,apartment,Pernambuco,Northeast,-8.142666,-34.906906,80.0,464129.36,5801.617000
...,...,...,...,...,...,...,...,...,...
12827,12828,house,São Paulo,Southeast,-23.595098,-46.796448,180.0,419213.60,2328.964444
12828,12829,house,São Paulo,Southeast,-23.587495,-46.559401,250.0,429194.89,1716.779560
12829,12830,apartment,São Paulo,Southeast,-23.522029,-46.189290,55.0,252398.80,4589.069091
12830,12831,apartment,São Paulo,Southeast,-23.526443,-46.529182,57.0,319400.84,5603.523509
12832,12833,apartment,Tocantins,North,-10.249091,-48.324286,70.0,289457.01,4135.100143

## Criação de coluna de preço por m2

In [45]:
df['price_per_m2'] = df['price_brl'] / df['area_m2']

In [46]:
df

,Unnamed: 0,property_type,state,region,lat,lon,area_m2,price_brl,price_per_m2
0,1,apartment,Pernambuco,Northeast,-8.134204,-34.906326,72.0,414222.98,5753.096944
1,2,apartment,Pernambuco,Northeast,-8.126664,-34.903924,136.0,848408.53,6238.298015
2,3,apartment,Pernambuco,Northeast,-8.125550,-34.907601,75.0,299438.28,3992.510400
3,4,apartment,Pernambuco,Northeast,-8.120249,-34.895920,187.0,848408.53,4536.944011
4,5,apartment,Pernambuco,Northeast,-8.142666,-34.906906,80.0,464129.36,5801.617000
...,...,...,...,...,...,...,...,...,...
12827,12828,house,São Paulo,Southeast,-23.595098,-46.796448,180.0,419213.60,2328.964444
12828,12829,house,São Paulo,Southeast,-23.587495,-46.559401,250.0,429194.89,1716.779560
12829,12830,apartment,São Paulo,Southeast,-23.522029,-46.189290,55.0,252398.80,4589.069091
12830,12831,apartment,São Paulo,Southeast,-23.526443,-46.529182,57.0,319400.84,5603.523509
12832,12833,apartment,Tocantins,North,-10.249091,-48.324286,70.0,289457.01,4135.100143